version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elasticsearch
    environment:
      - node.name=es01
      - discovery.type=single-node
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    networks:
      - elasticsearch
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: kibana
    networks:
      - elasticsearch
    ports:
      - 127.0.0.1:9400:9400
      - 127.0.0.1:5601:5601
    depends_on:
      - elasticsearch

volumes:
  elasticsearch:
    external: true

networks:
  elasticsearch:
    external: true