name: "regleringsbrev"
fs:
  url: "/runtime/data/"
  update_rate: "10m"
  excludes:
    - "*/.DS_Store"
    - ".gitkeep"
  json_support: false
  filename_as_id: true
  add_filesize: true
  remove_deleted: true
  add_as_inner_object: false
  store_source: false
  index_content: true
  attributes_support: false
  raw_metadata: false
  xml_support: false
  index_folders: false
  lang_detect: false
  continue_on_error: false
  ocr:
    enabled: true
    pdf_strategy: "ocr_and_text"
  follow_symlinks: false
  indexed_chars: "-1"
elasticsearch:
  nodes:
    - url: "167.172.191.58:9200"
  bulk_size: 100
  flush_interval: "5s"
  byte_size: "10mb"
